# Generated by Django 2.1 on 2020-04-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Step',
        ),
    ]
